name: Deploy Storybook

on:
  push:
    branches:
      - main
    paths:
      - "packages/ui/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies and build Storybook
        run: |
          npm install
          npm run sb:build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: "packages/ui/storybook-static"
